Flex grid homework
dragan-andrei/Tekwill_FE_gr11 pull request #10
Opened 2024-04-07 02:40 UTC by dragan-andrei

# Flex&Grid. I can say that this Homework About all knolegde that we have about HTML&CSS.

https://github.com/dragan-andrei/Tekwill_FE_gr11/assets/161748972/df91b67b-5abe-4b4b-bb5d-5ed400d02326

### Это головоломка. Работа собрала в себя все темы, которые мы прошли до сих пор. Очень объемное, интересное и отчасти сложное задание. Я не доволен тем, что у меня никак не получилось отцентровать мои *МЯУ* и *ГАВ*. 
### Выкладываю, можно сказать *заранее*. Может, если будет возможность, то вы сможете мне что-нибудь подсказать, чтобы до 9 числа работа была готова 😄

2024-04-07 09:47 UTC, CozlovschiNichita approved these changes
it's hard

2024-04-17 14:36 UTC, IvanCeban requested changes
You did great job!
The page looks nice and responsiveness is great!
Just cleanup a bit your css (follow DRY principle - Don't repeat yourself)

2024-04-17 14:36 UTC, IvanCeban commented on cats.css
> +    position: relative;
Try ```position: absolute; display: flex, and align-items:center; justify-content: center```
In this case you will resolve issue with centering the content.

2024-04-17 14:36 UTC, IvanCeban commented on cats.css
> +.rightsidebar div.dog1:hover .woff {
No need to repeat opacity props. 
You can set it just once:
```
.rightsidebar>div:hover .woff {
    opacity: 1;
}```

2024-04-17 14:36 UTC, IvanCeban commented on cats.css
> +    background-position: center;
dont repeat yourself. 
for example ```background-position and background-size``` are the same for all cats

2024-04-17 14:36 UTC, IvanCeban commented on cats.css
> +    top: 94%;
better use position absolute for "meo". Will be more flexible positioning

2024-04-17 14:36 UTC, IvanCeban commented on cats.css
> +.mainpole .cat2:hover .meo {
Don't repeat yourself.

2024-04-18 18:02 UTC, dragan-andrei commented
> You did great job! The page looks nice and responsiveness is great! Just cleanup a bit your css (follow DRY principle - Don't repeat yourself)

Thank you! Now my code looks much better. It became more readable and it became clearer to me what was going on.

2024-04-23 14:58 UTC, IvanCebanPVT approved these changes
Great job!

2024-04-23 14:59 UTC, IvanCeban approved these changes
Great Job!

2024-05-07 11:09 UTC, merged